"""Authentication Credentials

Add your Tidal Migrations credentials.
   - tidal_subdomain is the name of your workspace.
"""
tidal_subdomain = "trreb"
tidal_email = "dev@trreb.com"
tidal_password = "myPassword"


"""Machine Stats output file name

Please include the relative path to the file generated by Machine Stats, if the file is not in the same directory. `../dir/example_payload.json`
"""
payload_json_file_name = "example_payload.json"


"""How to measure fields

The fields that need to be tracked can be added in the fields_to_measure list.
If it's a custom field, please add it to the custom_fields_to_measure list.
"""
fields_to_measure = ["ram_used_gb"]
custom_fields_to_measure = ['cpu_average', 'cpu_peak']


"""How to use is_using_configs flag

`is_using_configs` variable is used to switch strategies to load credentials.
   - When True: Credentials and configs from this file will be used.
   - When False: The script will prompt you to enter the credentials and configs.
"""
is_using_configs = True
